## Linear Algebra Review using Numpy

Boise State University\
Department of Computer Science\
CS 334 Algorithms of Machine Learning\
Conrad Kennington\
Fall 2020

In [5]:
import numpy as np

Scalars, Vectors, Matrices and Tensors

<img style="float: left;" src="images/scalar.png" width="500">

## Example 1. Create a vector with Python and Numpy

This is just a 1-dimensional array.

In [8]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

## Example 2. Create a (3x2) matrix with nested brackets.

The array() function can also create 2-dimensional arrays with nested brackets.

In [9]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Shape

In [10]:
A.shape

(3, 2)

We can see that A has 3 rows and 2 columns.
Let’s check the shape of our first vector:

In [11]:
x.shape

(4,)

As expected, you can see that x has only one dimension. The number corresponds to the length of the array:

In [12]:
len(x)

4

## Example 3. Transposition

With transposition you can convert a row vector to a column vector and vice versa.\
Create a matrix A and transpose it

In [14]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
A.shape

(3, 2)

In [17]:
A_t.shape

(2, 3)

We can see that the number of columns becomes the number of rows with transposition and vice versa.

## Example 4. Addition

Matrices can be added if they have the same shape:\
A+B=C

Create two matrices A and B and add them

With Numpy you can add matrices just as you would add vectors or scalars.

In [19]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [21]:
# Add matrices A and B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

## Example 5. Add scalar to a matrix

In [22]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
# Exemple: Add 4 to the matrix A
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Example 6. Add two matrices of different shapes

In [24]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
B = np.array([[2], [4], [6]])
B

array([[2],
       [4],
       [6]])

In [26]:
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

Numpy can handle operations on arrays of different shapes. The smaller array will be extended to match the shape of the bigger one. The advantage is that this is done in C under the hood (like any vectorized operations in Numpy). Actually, we used broadcasting in the example 5. The scalar was converted in an array of same shape as A.

## These functions are used in many Machine Learning Algorithms.